### ISSUE TITLE
AttributeError: 'GeventWebSocketClient' object has no attribute 'recv'

### ISSUE THREAD

**Issue by jaapz** [zeekay/flask-uwsgi-websocket#18]
The GeventWebSocketClient does not expose the same interface as normal WebSocket, making it just a tad bit harder to move from WebSocket to GeventWebSocket. GeventWebSocket misses the recv method, while WebSocket does have it.

Please add recv as a alias of recieve on GeventWebSocket.

**Comment by zeekay** [comment]
Oops, good catch!

**Comment by jaapz** [comment]
Nice, quick response! :+1:
