### ISSUE TITLE
Timeouts On Connection When Using uwsgi/nginx

### ISSUE THREAD

**Issue by rholloway** [zeekay/flask-uwsgi-websocket#19]
With Flask-uwsgi-websocket, are we supposed to manage ping/pong to keep the connection alive manually?

For me, the connection dies after a minute or so. I'm running nginx 1.6 in front of uwsgi 2.0 serving the Flask application. The uwsgi documentation on websockets makes it sound like uwsgi websockets take care of it for us in the background, but I'm not sure if that is the case. Also, I'm not sure if it makes a difference, but currently I'm using websockets only to allow clients to subscribe to messages - that is, the client only calls recv() and the server is only calling send(). It sounds like some of the ping/pong is built in to the recv_nb() call for native uwsgi websockets - I'm not sure how that translates to flask-uwsgi-websockets. I tried tossing in a ws.receive() on the server within the infinite loop (reading messages from redis, pushing out to clients over websockets), but that didn't seem to work either.

If not, is there a recommended way or example to handle this using flask-uwsgi-websocket?

--UPDATE--

It does seem like I've been able to resolve the dying connection by manually adding ping/pong into both server and client script. On the server, I check if it's been > 15 seconds since the last "heartbeat", and if so it sends a message and then calls ws.receive(), the client receives, interprets as heartbeat, and sends a message back. This does resolve the issue, but is that the best way to handle this? Ideally (in my mind) the client wouldn't have to code up this logic and can just receive messages as they become available, but perhaps there isn't an easier way.

**Comment by jaapz** [comment]
Can you post your nginx config?

**Comment by zeekay** [comment]
Glad you resolved things! I lowered the default timeout which should take better advantage of uWSGI's PING/PONG and make connections longer-lived in general. Locally I am not having any issue with 5+ minute connections.

**Comment by ser** [comment]
I still have no idea how to use "automatic" pings/pongs and had to deploy them in my code separately.
