### ISSUE TITLE
Uwsgi path incorrect since merging #24

### ISSUE THREAD

**Issue by obiesmans** [zeekay/flask-uwsgi-websocket#28]
Since merging #24, the path of uwsgi is wrong. #24 says that uwsgi is always in the same directory as a python interpreter, but it's not the case for me.
I use my distro's python, and uwsgi is installed using the [user scheme](https://pip.pypa.io/en/latest/user_guide.html#user-installs), so python is in /usr/bin and uwsgi in ~/.local/bin (or rather [site.USER_BASE](https://docs.python.org/3/library/site.html#site.USER_BASE)).

**Comment by zeekay** [comment]
Unfortunately `site.USER_BASE` isn't consistent across platforms either. I should probably just revert #24, previously you could just modify `$PATH` to ensure the proper uwsgi was found.

**Comment by Ivoz** [comment]
I think the case that "uswgi will be next to the python binary" is just as arbitrarily sometimes true as "the right uswgi is the one first found on the path", sometimes one or either could be completely wrong. One might be in a virtualenv and want to use a system-install uwsgi, or want to use a virtualenv-installed uwsgi, or be in a global python and want to use a custom compiled uwsgi `/somwhere/`.

#24 was stating their own use case as the objective truth.

I think "find the first one on the path" is the most reasonable guess, but also providing a way to configure the uwsgi binary to use would be great. For instance, also query if a `FLASK_UWSGI_BINARY` environment key exists and use its value if so. You could also pull out a `uwsgi_binary` from `**kwargs` in `Websocket.run`. then `os.environ.get('FLASK_UWSGI_BINARY')` > `run(uwsgi_binary='')` > `uwsgi`.

**Comment by zeekay** [comment]
Makes sense to me.
