### ISSUE TITLE
KeyError Exception raised from `threading` module on script shutdown

### ISSUE THREAD

**Issue by emve-dev** [zeekay/flask-uwsgi-websocket#29]
When closing dev server with Ctrl+C i get this error:
`Exception KeyError: KeyError(139689878552080,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored`

I think the issue is that somewhere in the code `threading` module is imported before `monkey_patch` is called (as described here: http://stackoverflow.com/questions/8774958/keyerror-in-module-threading-after-a-successful-py-test-run).

But I moved my imports to the top of the file like so:

``` python
from flask_uwsgi_websocket import GeventWebSocket
from flask import Flask, render_template, jsonify, request
# Create app
app = Flask(__name__)
ws = GeventWebSocket(app)
```

and still get the error.

However, if I comment last line `ws = GeventWebSocket(app)` the error disapears.

Any help please?

**Comment by zeekay** [comment]
As far as I know this is relatively harmless...?

**Comment by emve-dev** [comment]
I hope so too. My concern is that in production it could lead to memory leaks. I'm not python ninja but that error is raised when process is terminating and threads created by geven couldn't be cleared. Maybe I'm wrong.

**Comment by emve-dev** [comment]
@zeekay is this error common when using GeventWebSocket?

**Comment by zeekay** [comment]
It's just a common error in general when using threading module and ctrl-c'ing.

**Comment by emve-dev** [comment]
Okay. Thanks for the response. I'll close the issue.
