### ISSUE TITLE
cant connect socket with lastest gevent & uwsgi

### ISSUE THREAD

**Issue by keiser1080** [zeekay/flask-uwsgi-websocket#50]
hi,
flask-uwsgi-websocket don't work with a fresh virtualenvironement.
```
pip freeze
Flask==0.10.1
Flask-uWSGI-WebSocket==0.5.2
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.9
argparse==1.2.1
distribute==0.6.34
gevent==1.1.1
greenlet==0.4.9
itsdangerous==0.24
uWSGI==2.0.12
wsgiref==0.1.2


uwsgi --master --http 0.0.0.0:8081 --http-websockets --gevent 100 --wsgi echo:app
```

the html page work but the socket can not be initialised.
No error on the log.

i'm pretty sure my configuration is correct because i am able to run this https://github.com/unbit/uwsgi/blob/master/tests/websockets.py

**Comment by keiser1080** [comment]
ok it's my faute.

please update all example with this 

```ws = new WebSocket("ws://" + document.location.hostname + ":" + document.location.port + "/websocket");```

in place of 

```var ws = new WebSocket('ws://127.0.0.1:5000/websocket');```

**Comment by Ivoz** [comment]
@keiser1080 the front-facing websocket server is not necessarily listening on the same port as the user visited the web page on. I think for an example, `127.0.0.1` is fine. Most people should know to change that if their server is listening on a different address.
