### ISSUE TITLE
Sending data as binary

### ISSUE THREAD

**Issue by rakeshrm** [zeekay/flask-uwsgi-websocket#52]
Is sending data with opcode BINARY supported?
I see that `send` takes a parameter `binary`, and it also has `send_binary` method. Whatever method I call, it always sends the data as TEXT.
The code for `send` and `send_binary` seems to be doing the same thing!

```

    def send(self, msg, binary=True):
        if binary:
            return self.send_binary(msg)
        self.send_queue.put(msg)
        self.send_event.set()

    def send_binary(self, msg):
        self.send_queue.put(msg)
        self.send_event.set()
```
Am I missing something, or is binary opcode not supported?

**Comment by zeekay** [comment]
It's not yet supported with gevent, but is pretty easy to add.

**Comment by rakeshrm** [comment]
Thanks. I have added a 'hack' to make this work. It will be good to have the support though.
