### ISSUE TITLE
Incompatibility with Python 3.7.0

### ISSUE THREAD

**Issue by rosensama** [zeekay/flask-uwsgi-websocket#67]
In python 3.7 `async` has become a keyword.   So `async.py` will need to be renamed and imported under the new name.  

      File "/path/to/venv/lib/python3.7/site-packages/flask_uwsgi_websocket/__init__.py", line 16
        from .async import *
                  ^
    SyntaxError: invalid syntax

**Comment by djlambert** [comment]
Could you release a new version so this PR is available on PyPi?

**Comment by zeekay** [comment]
Updated!

**Comment by djlambert** [comment]
Thanks!
